

GET http://localhost:3000/users
Content-Type: application/json



POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Matheus",
    "email": "matheus@gmail.com",
    "password": "Tetew"
}



POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "matheus@gmail.com",
    "password": "Tetew"
}